In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Main.csv')

C:\Users\Acer\AppData\Roaming\Python\Python36\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (8,9,10,11,12,13) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

## Data Preparation

In [3]:
df.dropna(subset=['Total Sales'],inplace=True)
df.drop(['Total Shipped'],axis =1 ,inplace=True)

In [4]:
df.reset_index(inplace=True)
df

,index,Position,Game Name,Console,Publisher,Developer,VGChartz Score,Critic Score,User Score,Total Sales,NA Sales,PAL Sales,Japan Sales,Other Sales,Release Date,Last Update
0,160,161,Grand Theft Auto V,PS3,Rockstar Games,Rockstar North,9.5,9.4,N/A,20.32m,6.37m,9.85m,0.99m,3.12m,17th Sep 13,NaN
1,186,187,Grand Theft Auto V,PS4,Rockstar Games,Rockstar North,N/A,9.7,N/A,19.39m,6.06m,9.71m,0.60m,3.02m,18th Nov 14,03rd Jan 18
2,219,220,Grand Theft Auto: Vice City,PS2,Rockstar Games,Rockstar North,N/A,9.6,N/A,16.15m,8.41m,5.49m,0.47m,1.78m,28th Oct 02,NaN
3,225,226,Grand Theft Auto V,X360,Rockstar Games,Rockstar North,N/A,N/A,N/A,15.86m,9.06m,5.33m,0.06m,1.42m,17th Sep 13,NaN
4,231,232,Call of Duty: Black Ops 3,PS4,Activision,Treyarch,N/A,N/A,N/A,15.09m,6.18m,6.05m,0.41m,2.44m,06th Nov 15,14th Jan 18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18866,23014,23165,"Mind, Body & Soul: Blend It!",DS,505 Games,Crush Digital,N/A,N/A,N/A,0.00m,NaN,0.00m,NaN,NaN,23rd Apr 10,NaN
18867,23015,23166,Ride! Carnival Tycoon,PC,ValuSoft,ValuSoft,N/A,N/A,N/A,0.00m,NaN,0.00m,NaN,NaN,01st Aug 07,NaN
18868,23016,23167,Shinobido: Tales of the Ninja,PSP,Sony Computer Entertainment,Acquire,N/A,N/A,N/A,0.00m,NaN,0.00m,NaN,NaN,09th Feb 07,NaN
18869,23017,23168,Tactical Ops: Assault on Terror,PC,Atari,Kamehan Studios,N/A,N/A,N/A,0.00m,NaN,0.00m,NaN,NaN,24th Apr 02,NaN
18870,23018,23169,World in Conflict: Soviet Assault,PC,Ubisoft,Massive Entertainment / Swordfish Studios,N/A,6.1,N/A,0.00m,NaN,0.00m,NaN,NaN,10th Mar 09,NaN

In [5]:
df.drop(['index','Position'],axis =1 ,inplace=True)

In [6]:
df

,Game Name,Console,Publisher,Developer,VGChartz Score,Critic Score,User Score,Total Sales,NA Sales,PAL Sales,Japan Sales,Other Sales,Release Date,Last Update
0,Grand Theft Auto V,PS3,Rockstar Games,Rockstar North,9.5,9.4,N/A,20.32m,6.37m,9.85m,0.99m,3.12m,17th Sep 13,NaN
1,Grand Theft Auto V,PS4,Rockstar Games,Rockstar North,N/A,9.7,N/A,19.39m,6.06m,9.71m,0.60m,3.02m,18th Nov 14,03rd Jan 18
2,Grand Theft Auto: Vice City,PS2,Rockstar Games,Rockstar North,N/A,9.6,N/A,16.15m,8.41m,5.49m,0.47m,1.78m,28th Oct 02,NaN
3,Grand Theft Auto V,X360,Rockstar Games,Rockstar North,N/A,N/A,N/A,15.86m,9.06m,5.33m,0.06m,1.42m,17th Sep 13,NaN
4,Call of Duty: Black Ops 3,PS4,Activision,Treyarch,N/A,N/A,N/A,15.09m,6.18m,6.05m,0.41m,2.44m,06th Nov 15,14th Jan 18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18866,"Mind, Body & Soul: Blend It!",DS,505 Games,Crush Digital,N/A,N/A,N/A,0.00m,NaN,0.00m,NaN,NaN,23rd Apr 10,NaN
18867,Ride! Carnival Tycoon,PC,ValuSoft,ValuSoft,N/A,N/A,N/A,0.00m,NaN,0.00m,NaN,NaN,01st Aug 07,NaN
18868,Shinobido: Tales of the Ninja,PSP,Sony Computer Entertainment,Acquire,N/A,N/A,N/A,0.00m,NaN,0.00m,NaN,NaN,09th Feb 07,NaN
18869,Tactical Ops: Assault on Terror,PC,Atari,Kamehan Studios,N/A,N/A,N/A,0.00m,NaN,0.00m,NaN,NaN,24th Apr 02,NaN
18870,World in Conflict: Soviet Assault,PC,Ubisoft,Massive Entertainment / Swordfish Studios,N/A,6.1,N/A,0.00m,NaN,0.00m,NaN,NaN,10th Mar 09,NaN

In [7]:
dfm = df[['Game Name','Console','Publisher','Developer','Last Update','NA Sales','PAL Sales','Japan Sales','Other Sales']]

In [17]:
output = (dfm.set_index(['Game Name','Console','Publisher','Developer','Last Update'])
   .stack(dropna=False)
   .reset_index()
   .rename({'level_5': 'Region', '0':'Sales'}, axis=1))

In [18]:
output

,Game Name,Console,Publisher,Developer,Last Update,Region,0
0,Grand Theft Auto V,PS3,Rockstar Games,Rockstar North,NaN,NA Sales,6.37m
1,Grand Theft Auto V,PS3,Rockstar Games,Rockstar North,NaN,PAL Sales,9.85m
2,Grand Theft Auto V,PS3,Rockstar Games,Rockstar North,NaN,Japan Sales,0.99m
3,Grand Theft Auto V,PS3,Rockstar Games,Rockstar North,NaN,Other Sales,3.12m
4,Grand Theft Auto V,PS4,Rockstar Games,Rockstar North,03rd Jan 18,NA Sales,6.06m
...,...,...,...,...,...,...,...
75479,Tactical Ops: Assault on Terror,PC,Atari,Kamehan Studios,NaN,Other Sales,NaN
75480,World in Conflict: Soviet Assault,PC,Ubisoft,Massive Entertainment / Swordfish Studios,NaN,NA Sales,NaN
75481,World in Conflict: Soviet Assault,PC,Ubisoft,Massive Entertainment / Swordfish Studios,NaN,PAL Sales,0.00m
75482,World in Conflict: Soviet Assault,PC,Ubisoft,Massive Entertainment / Swordfish Studios,NaN,Japan Sales,NaN
75483,World in Conflict: Soviet Assault,PC,Ubisoft,Massive Entertainment / Swordfish Studios,NaN,Other Sales,NaN

In [84]:
dfm.stack(dropna=False).reset_index()

                                   Game Name      level_1      0
0                     Grand Theft Auto V         NA Sales  6.37m
1                     Grand Theft Auto V        PAL Sales  9.85m
2                     Grand Theft Auto V      Japan Sales  0.99m
3                     Grand Theft Auto V      Other Sales  3.12m
4                     Grand Theft Auto V         NA Sales  6.06m
...                                      ...          ...    ...
75479    Tactical Ops: Assault on Terror      Other Sales    NaN
75480  World in Conflict: Soviet Assault         NA Sales    NaN
75481  World in Conflict: Soviet Assault        PAL Sales  0.00m
75482  World in Conflict: Soviet Assault      Japan Sales    NaN
75483  World in Conflict: Soviet Assault      Other Sales    NaN

[75484 rows x 3 columns]

## OUTPUT

In [16]:
output.to_csv('New.csv')

In [81]:
df.to_csv('Out.csv')